version: 1.0
jobs:
  hello:
    steps:
      - sleep 60
      - echo "Hello!!ghdfsfadsfsd"
  world:
    steps:
      - echo "World!!"
  hello-world:
    steps:
      - echo "Hello!"
stages:
  - name: build
    jobs:
      - hello
      - hello-world