version: 1
jobs:
  hello:
    image: test
    steps:
      - echo "Hehjbhjljigc"
  world:
    steps:
      - echo "World!!"
  hello-world:
    steps:
      - echo "Hello!"
stages:
  - name: build
    jobs:
      - hello
      - hello-world
images:
  test:
    image: test-image
    registry: registry.hub.docker.com/vipinkumarh/test-image:latest
    auth:
      username: vipinkumarh
      password: Catalyst@2