version: 1
jobs:
  hello:
    image: test
    steps:
      - echo "Hehjbhjljijhgco"
  world:
    steps:
      - echo "World!!"
  hello-world:
    steps:
      - echo "Hello!"
stages:
  - name: build
    jobs:
      - hello
      - hello-world
images:
  test:
    image: node:20
    auth:
      username: vipinkumarh
      password: Catalyst@2