version: 1.0
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "Wo"
  hello-world:
    steps:
      - echo "Hello Worl"
stages:
  - name: build
    jobs:
      - hello
      - hello-world