version: 1.0
jobs:
  hello:
    steps:
      - sleep 120
      - echo "Hellooo"
  world:
    steps:
      - echo "World!!"
  hello-world:
    steps:
      - echo "Hello!"
stages:
  - name: build
    jobs:
      - hello
      - hello-world