version: 1.0
pipeline-when:
  or:
      - equal:
          - << event.ref >>
          - refs/heads/mai
      - equal:
          - << event.ref >>
          - refs/heads/main
jobs:
  hello:
    steps:
      - sleep 120
      - echo "Hehjbhjljijhgco"
  world:
    steps:
      - echo "World!!"
  hello-world:
    steps:
      - echo "Hello!"
stages:
  - name: build
    jobs:
      - hello
      - hello-world