version: 1
jobs:
  angular-test:
    steps:
      - ls
stages:
  - name: test
    jobs:
      - angular-test
images:
  TestUbuntuImage:
    image: vipinkumarh/test-image:latest
    registry: registry.hub.docker.com
    auth:
      username: vipinkumarh
      password: Catalyst@2
pipeline-image: TestUbuntuImage