version: 1.1
jobs:
  hello:
    steps:
      - ls
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!!!"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world